name: Build
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
         path: .gradle/loom-cache
         key: ${{runner.os}}-loom-cache-${{hashFiles("**/build.gradle")}}
      - uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.1
          arguments: clean build
      - uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build/libs
